### ISSUE TITLE
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.shfl.sync.bfly.i32

### ISSUE THREAD

**Issue by sasha0552** [sasha0552/triton#1]
```
INFO:     x.x.x.x:xxxxx - "POST /v1/chat/completions HTTP/1.1" 200 OK
[Detaching after vfork from child process 3233]
[Detaching after vfork from child process 3234]
[New Thread 0x7ffe89c006c0 (LWP 3235)]
[New Thread 0x7ffe892006c0 (LWP 3236)]
INFO 04-26 15:39:44 metrics.py:229] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.3%, CPU KV cache usage: 0.0%
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.shfl.sync.bfly.i32

Thread 41 "python3" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffe8a6006c0 (LWP 3219)]
0x00007ffff788632c in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff788632c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff78356c8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff781d4b8 in abort () from /usr/lib/libc.so.6
#3  0x00007fff3138dd30 in llvm::report_fatal_error(llvm::Twine const&, bool) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#4  0x00007fff3025cf6d in llvm::SelectionDAGISel::CannotYetSelect(llvm::SDNode*) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#5  0x00007fff3025c03b in llvm::SelectionDAGISel::SelectCodeCommon(llvm::SDNode*, unsigned char const*, unsigned int) ()
   from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#6  0x00007fff30250745 in llvm::SelectionDAGISel::DoInstructionSelection() () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#7  0x00007fff3024f635 in llvm::SelectionDAGISel::CodeGenAndEmitDAG() () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#8  0x00007fff3024ce76 in llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#9  0x00007fff302495ff in llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#10 0x00007fff305c7e4f in llvm::MachineFunctionPass::runOnFunction(llvm::Function&) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#11 0x00007fff3125ffdf in llvm::FPPassManager::runOnFunction(llvm::Function&) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#12 0x00007fff31266b21 in llvm::FPPassManager::runOnModule(llvm::Module&) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#13 0x00007fff312606e1 in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /home/tori/vllm/venv/lib/python3.11/site-packages/triton/_C/libtriton.so
#14 0x00007fff3153805a in triton::translateLLVMIRToPTX[abi:cxx11](llvm::Module&, int, int, bool) (module=..., cc=cc@entry=61, version=version@entry=83, 
    enable_fp_fusion=enable_fp_fusion@entry=true) at /tmp/pip-req-build-tydn7d13/lib/Target/PTX/PTXTranslation.cpp:113
#15 0x00007fff2ff9f59e in operator() (
    llvmIR="; ModuleID = 'LLVMDialectModule'\nsource_filename = \"LLVMDialectModule\"\n\n@global_smem = external local_unnamed_addr addrspace(3) global [0 x i8]\n\ndefine void @_fwd_kernel_0d1d2d3d4d5d67d8d9d10de11e12d1"..., capability=capability@entry=61, version=version@entry=83, enable_fp_fusion=enable_fp_fusion@entry=true, __closure=<optimized out>)
    at /tmp/pip-req-build-tydn7d13/python/src/triton.cc:1899
#16 0x00007fff2ffc0af6 in pybind11::detail::argument_loader<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, bool>::call_impl<std::__cxx11::basic_string<char>, init_triton_translation(pybind11::module&)::<lambda(std::string, int, int, bool)>&, 0, 1, 2, 3, pybind11::detail::void_type> (f=..., this=0x7ffe8a5fbf60)
    at /home/tori/.triton/pybind11/pybind11-2.11.1/include/pybind11/detail/../cast.h:1480
#17 pybind11::detail::argument_loader<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, int, bool>::call<std::__cxx11::basic_string<char>, pybind11::detail::void_type, init_triton_translation(pybind11::module&)::<lambda(std::string, int, int, bool)>&> (f=..., this=0x7ffe8a5fbf60)
    at /home/tori/.triton/pybind11/pybind11-2.11.1/include/pybind11/detail/../cast.h:1449
#18 operator() (__closure=0x0, call=...) at /home/tori/.triton/pybind11/pybind11-2.11.1/include/pybind11/pybind11.h:253
#19 _FUN () at /home/tori/.triton/pybind11/pybind11-2.11.1/include/pybind11/pybind11.h:224
#20 0x00007fff2ff957b2 in pybind11::cpp_function::dispatcher (self=<optimized out>, args_in=0x7ffec0f76750, kwargs_in=0x0)
    at /home/tori/.triton/pybind11/pybind11-2.11.1/include/pybind11/pybind11.h:946
#21 0x00007ffff7bd8d41 in ?? () from /usr/lib/libpython3.11.so.1.0
#22 0x00007ffff7bb7054 in _PyObject_MakeTpCall () from /usr/lib/libpython3.11.so.1.0
#23 0x00007ffff7bc26e1 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#24 0x00007ffff7c09583 in ?? () from /usr/lib/libpython3.11.so.1.0
#25 0x00007ffff7c08f9e in ?? () from /usr/lib/libpython3.11.so.1.0
#26 0x00007ffff7bf42fc in PyObject_Call () from /usr/lib/libpython3.11.so.1.0
#27 0x00007ffff7cb4631 in ?? () from /usr/lib/libpython3.11.so.1.0
#28 0x00007ffff7bb7054 in _PyObject_MakeTpCall () from /usr/lib/libpython3.11.so.1.0
#29 0x00007ffff7bf42fc in PyObject_Call () from /usr/lib/libpython3.11.so.1.0
#30 0x00007ffff7bc66a3 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
#31 0x00007ffff7be98c0 in _PyFunction_Vectorcall () from /usr/lib/libpython3.11.so.1.0
#32 0x00007ffff7bc66a3 in _PyEval_EvalFrameDefault () from /usr/lib/libpython3.11.so.1.0
--Type <RET> for more, q to quit, c to continue without paging--
```

**Comment by sasha0552** [comment]
Fixed in https://github.com/sasha0552/triton/commit/d224513c7bfeaf0fc7f8fda28fff21101e7c8212
